schema {
  query: RootQuery
  mutation: RootMutation
}

type BasketObjectType {
  created: DateTime!
  productInventory: ProductInventoryType
  quantity: Int!
  updated: DateTime!
  webId: String!
}

type BasketType {
  basketObjects: [BasketObjectType!]!
  created: DateTime!
  totalPrice: Decimal!
  totalQty: Int!
  updated: DateTime!
  webId: String!
}

type BrandType {
  name: String!
  slug: String!
}

type CaptchaType {
  image: String!
  webId: String!
}

type CategoryType {
  name: String!
  slug: String!
}

"""Date with time (isoformat)"""
scalar DateTime

"""Decimal (fixed-point)"""
scalar Decimal

type DeleteType {
  deleted: Boolean!
}

"""The `JSON` scalar type represents JSON values as specified by ECMA-404"""
scalar JSON

type MeType {
  dateJoined: DateTime!
  email: String!
  firstName: String!
  isActive: Boolean!
  isStaff: Boolean!
  isSuperuser: Boolean!
  lastLogin: DateTime!
  lastName: String!
  profileImage: String!
  username: String!
}

type MediaType {
  imgUrl: String!
}

type OrderInvoiceType {
  createdAt: DateTime!
  expiredAt: DateTime!
  invoiceId: String!
  invoiceUrl: String!
  price: Float!
}

type OrderType {
  basket: BasketType!
  city: String!
  email: String!
  firstname: String!
  invoice: OrderInvoiceType
  lastname: String!
  street: String!
  zipCode: String!
}

type PayloadType {
  payload: TokenPayloadType!
}

type ProductAttributeType {
  name: String!
}

type ProductAttributeValueType {
  attributeValue: String!
  productAttribute: ProductAttributeType!
}

type ProductInventoryType {
  attributeValues: [ProductAttributeValueType!]!
  attributes: JSON!
  brand: BrandType
  isActive: Boolean!
  isDefault: Boolean!
  product: ProductType!
  productImages: [MediaType!]!
  retailPrice: Decimal!
  salePrice: Decimal!
  sku: String!
  storePrice: Decimal!
  upc: String!
}

type ProductType {
  category: [CategoryType!]!
  createdAt: String!
  defaultImage: MediaType
  description: String!
  isActive: Boolean!
  name: String!
  owner: UserType!
  product: [ProductInventoryType!]!
  slug: String!
  startingFromPrice: Decimal!
  updatedAt: String!
  webId: String!
}

type ProductTypePaginationWindow {
  """The list of items in this pagination window."""
  items: [ProductType!]!

  """Total number of items in the filtered dataset."""
  totalItemsCount: Int!
}

type RefreshedTokenType {
  payload: TokenPayloadType!
  refreshExpiresIn: Int!
  refreshToken: String!
  token: String!
}

type RootMutation {
  addToBasket(productInventorySku: String!, quantity: Int!, webId: String!): BasketType!
  createBasket: BasketType!
  createCaptcha: CaptchaType!
  createOrder(basketWebId: String!, captchaText: String!, captchaWebId: String!, city: String!, email: String!, firstname: String!, lastname: String!, street: String!, zipCode: String!): OrderType!
  deleteBasket(webId: String!): BasketType!
  deleteTokenCookie: DeleteType!
  emptyBasket(webId: String!): BasketType!
  refreshToken(refreshToken: String, token: String): RefreshedTokenType!
  removeFromBasket(productInventorySku: String!, webId: String!): BasketType!
  submitCaptcha(captchaText: String!, webId: String!): Boolean!
  tokenAuth(password: String!, refreshToken: String, token: String, username: String!): TokenDataType!
  updateBasket(productInventoryId: String!, quantity: Int!, webId: String!): BasketType!
  verifyToken(token: String!): PayloadType!
}

type RootQuery {
  basket(webId: String!): BasketType!
  invoices: [JSON!]!
  me: MeType
  productByWebId(webId: String!): ProductType
  productInventoriesBySkus(skus: [String!]!): [ProductInventoryType!]!
  productInventoryBySku(sku: String!): ProductInventoryType
  products(category: String = null, limit: Int! = 20, offset: Int! = 0, search: String = null, user: String = null): ProductTypePaginationWindow!
  systemStatus: SystemStatus!
  top20Users: [UserType!]!
  user(username: String!): UserType!
}

type SystemStatus {
  machine: String!
  processor: String!
  release: String!
  system: String!
  version: String!
}

type TokenDataType {
  payload: TokenPayloadType!
  refreshExpiresIn: Int
  refreshToken: String
  token: String!
}

type TokenPayloadType {
  exp: Int!
  origIat: Int!
  username: String!
}

type UserType {
  dateJoined: DateTime!
  isActive: Boolean!
  isStaff: Boolean!
  isSuperuser: Boolean!
  products: [ProductType!]!
  profileImage: String!
  username: String!
}
