schema {
  query: RootQuery
  mutation: RootMutation
}

type BasketObjectType {
  createdAt: DateTime!
  productInventory: ProductInventoryType
  quantity: Int!
  updatedAt: DateTime!
  webId: String!
}

type BasketType {
  basketObjects: [BasketObjectType!]!
  createdAt: DateTime!
  order: OrderType
  totalPrice: Decimal!
  totalQty: Int!
  updatedAt: DateTime!
  vendorBasketObjects: [BasketObjectType!]!
  webId: String!
}

type BrandType {
  name: String!
  webId: String!
}

type CaptchaType {
  image: String!
  webId: String!
}

type CategoryType {
  name: String!
  slug: String!
  webId: String!
}

"""Date with time (isoformat)"""
scalar DateTime

"""Decimal (fixed-point)"""
scalar Decimal

type DeleteType {
  deleted: Boolean!
}

"""The `JSON` scalar type represents JSON values as specified by ECMA-404"""
scalar JSON

type MeType {
  balance: Decimal!
  dateJoined: DateTime
  email: String!
  firstName: String!
  isActive: Boolean!
  isStaff: Boolean!
  isSuperuser: Boolean!
  lastLogin: DateTime
  lastName: String!
  profileImage: String!
  username: String!
}

input MediaInputType {
  image: Upload!
}

type MediaType {
  image: String!
  webId: String!
}

type OrderInvoiceType {
  createdAt: DateTime!
  expiredAt: DateTime!
  invoiceId: String!
  invoiceUrl: String!
  price: Float!
}

type OrderType {
  basket: BasketType!
  city: String!
  createdAt: DateTime
  email: String!
  firstname: String!
  invoice: OrderInvoiceType
  lastname: String!
  status: String!
  street: String!
  totalPrice: Decimal!
  webId: String!
  zipCode: String!
}

type PayloadType {
  payload: TokenPayloadType!
}

type ProductAttributeType {
  name: String!
  webId: String!
}

type ProductAttributeValueType {
  attributeValue: String!
  productAttribute: ProductAttributeType!
  webId: String!
}

type ProductInventoryType {
  attributeValues: [ProductAttributeValueType!]!
  attributes: JSON!
  brand: BrandType
  isActive: Boolean!
  isDefault: Boolean!
  product: ProductType!
  productImages: [MediaType!]!
  retailPrice: Decimal
  salePrice: Decimal
  sku: String
  stock: StockType
  storePrice: Decimal!
  upc: String
  webId: String!
}

type ProductType {
  category: [CategoryType!]!
  createdAt: String!
  defaultImage: MediaType
  description: String!
  inventories: [ProductInventoryType!]!
  isActive: Boolean!
  name: String!
  owner: UserType!
  slug: String!
  startingFromPrice: Decimal!
  updatedAt: String!
  webId: String!
}

type ProductTypePaginationWindow {
  """The list of items in this pagination window."""
  items: [ProductType!]!

  """Total number of items in the filtered dataset."""
  totalItemsCount: Int!
}

type ProductTypeType {
  name: String!
  webId: String!
}

type RefreshedTokenType {
  payload: TokenPayloadType!
  refreshExpiresIn: Int!
  refreshToken: String!
  token: String!
}

type RootMutation {
  addToBasket(basketWebId: String!, inventoryWebId: String!, quantity: Int!): BasketType!
  createBasket: BasketType!
  createCaptcha: CaptchaType!
  createOrder(basketWebId: String!, captchaText: String!, captchaWebId: String!, city: String!, email: String!, firstname: String!, lastname: String!, street: String!, zipCode: String!): OrderType!
  createProduct(category: String!, description: String!, name: String!): ProductType!
  createProductInventory(attributeValues: JSON = null, brandWebId: String = null, isActive: Boolean = false, isDefault: Boolean = false, media: [MediaInputType!] = null, productTypeWebId: String = null, productWebId: String!, storePrice: Decimal!, weight: Decimal = null): ProductInventoryType!
  deleteBasket(webId: String!): BasketType!
  deleteProduct(webId: String!): Boolean!
  deleteProductInventory(webId: String!): Boolean!
  deleteTokenCookie: DeleteType!
  emptyBasket(basketWebId: String!): BasketType!
  refreshToken(refreshToken: String, token: String): RefreshedTokenType!
  removeFromBasket(basketWebId: String!, inventoryWebId: String!): BasketType!
  submitCaptcha(captchaText: String!, webId: String!): Boolean!
  tokenAuth(password: String!, refreshToken: String, token: String, username: String!): TokenDataType!
  updateBasket(basketWebId: String!, inventoryWebId: String!, quantity: Int!): BasketType!
  verifyToken(token: String!): PayloadType!
}

type RootQuery {
  basket(webId: String!): BasketType!
  categories: [CategoryType!]!
  checkOrder(webId: String!): OrderType!
  inventoriesByWebIds(webIds: [String!]!): [ProductInventoryType!]!
  inventoryByWebId(webId: String!): ProductInventoryType
  invoices: [JSON!]!
  me: MeType
  meProducts(limit: Int! = 20, offset: Int! = 0): ProductTypePaginationWindow
  myOrders: [OrderType!]!
  productByWebId(webId: String!): ProductType
  productTypes: [ProductTypeType!]!
  products(category: String = null, limit: Int! = 20, offset: Int! = 0, search: String = null, user: String = null): ProductTypePaginationWindow!
  top20Users: [UserType!]!
  user(username: String!): UserType!
}

type StockType {
  units: Int!
  webId: String!
}

type TokenDataType {
  payload: TokenPayloadType!
  refreshExpiresIn: Int
  refreshToken: String
  token: String!
}

type TokenPayloadType {
  exp: Int!
  origIat: Int!
  username: String!
}

scalar Upload

type UserType {
  amountEarnedThisMonth: Float!
  dateJoined: DateTime!
  isActive: Boolean!
  isStaff: Boolean!
  isSuperuser: Boolean!
  products: [ProductType!]!
  profileImage: String!
  username: String!
}
