schema {
  query: RootQuery
  mutation: RootMutation
}

type CategoryType {
  name: String!
  slug: String!
}

"""Date with time (isoformat)"""
scalar DateTime

type DeleteType {
  deleted: Boolean!
}

"""The `JSON` scalar type represents JSON values as specified by ECMA-404"""
scalar JSON

type MeType {
  dateJoined: DateTime!
  email: String!
  firstName: String!
  isActive: Boolean!
  isStaff: Boolean!
  isSuperuser: Boolean!
  lastLogin: DateTime!
  lastName: String!
  profileImage: String!
  username: String!
}

type MediaType {
  imgUrl: String!
}

type OrderInvoiceType {
  createdAt: DateTime!
  expiredAt: DateTime!
  invoiceId: String!
  invoiceUrl: String!
  price: Float!
}

type OrderProductInventoryType {
  productInventory: ProductInventoryType!
  quantity: Int!
}

type OrderType {
  id: Int!
  invoices: [OrderInvoiceType!]!
  orderProductInventories: [OrderProductInventoryType!]!
  totalPrice: Float!
  totalQuantity: Int!
}

type PayloadType {
  payload: TokenPayloadType!
}

type ProdctType {
  category: CategoryType!
  createdAt: String!
  defaultImage: MediaType
  description: String!
  isActive: Boolean!
  name: String!
  product: [ProductInventoryType!]!
  slug: String!
  updatedAt: String!
  webId: String!
}

type ProductAttributeType {
  name: String!
}

type ProductAttributeValueType {
  attributeValue: String!
  productAttribute: ProductAttributeType!
}

type ProductInventoryType {
  attributeValues: [ProductAttributeValueType!]!
  attributes: JSON!
  isActive: Boolean!
  isDefault: Boolean!
  product: ProdctType!
  sku: String!
  upc: String!
}

type RefreshedTokenType {
  payload: TokenPayloadType!
  refreshExpiresIn: Int!
  refreshToken: String!
  token: String!
}

type RootMutation {
  createOrder(cart: JSON!): OrderType!
  deleteTokenCookie: DeleteType!
  refreshToken(refreshToken: String, token: String): RefreshedTokenType!
  setupBtcpayClient(code: String!, host: String!): Boolean!
  tokenAuth(password: String!, refreshToken: String, token: String, username: String!): TokenDataType!
  verifyToken(token: String!): PayloadType!
}

type RootQuery {
  btcpayClientHost: String!
  invoices: [JSON!]!
  me: MeType
  productByWebId(webId: String!): ProdctType
  productInventoriesBySkus(skus: [String!]!): [ProductInventoryType!]!
  productInventoryBySku(sku: String!): ProductInventoryType
  products: [ProdctType!]!
  systemStatus: SystemStatus!
}

type SystemStatus {
  machine: String!
  processor: String!
  release: String!
  system: String!
  version: String!
}

type TokenDataType {
  payload: TokenPayloadType!
  refreshExpiresIn: Int
  refreshToken: String
  token: String!
}

type TokenPayloadType {
  exp: Int!
  origIat: Int!
  username: String!
}
