query GetBasketQuery($webId: String!) {
	basket(webId: $webId) {
		basketObjects {
			quantity
			productInventory {
				webId
				storePrice
				productImages {
					image
				}
				product {
					name
					webId
					defaultImage {
						image
					}
				}
			}
		}
		webId
		totalPrice
		totalQty
	}
}
