query productByWebId($webId: String!) {
	productByWebId(webId: $webId) {
		webId
		name
		slug
		description
		isActive
		createdAt
		updatedAt
		defaultImage {
			imgUrl
		}
		category {
			name
			slug
		}
		product {
			sku
			attributes
		}
	}
}
